apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: my-kafka-0
spec:
  kafka:
    version: 4.1.1
    metadataVersion: 4.1-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: nodeport
        port: 19092
        type: nodeport
        tls: false
      - name: lb
        port: 29092
        type: loadbalancer
        tls: false
        configuration:
          loadBalancerSourceRanges:
            - 0.0.0.0/0
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
