apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: main
          image: ttl.sh/ondrejsika/example-keda-consumer
          env:
            - name: KAFKA_BROKER_ADDRESS
              value: target-cluster-kafka-bootstrap.kafka.svc:9092
            - name: KAFKA_TOPIC
              value: source-cluster.my-topic
            - name: KAFKA_GROUP_ID
              value: default
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
