apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: my-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: source-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.bytes: 536870912 # 512Mi per partition
