apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: my-cluster
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  template:
    pod:
      securityContext:
        fsGroup: 0
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: false
        kraftMetadata: shared
      - id: 1
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
      - id: 2
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
      - id: 3
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
