apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: k-4
  namespace: kafka
spec:
  kafka:
    version: 3.3.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: extplain
        port: 9094
        type: nodeport
        tls: false
      - name: exttls
        port: 9095
        type: nodeport
        tls: true
        authentication:
          type: tls
    authorization:
      type: simple
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 1Gi
          deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
