apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: k-4-t-1
  labels:
    strimzi.io/cluster: k-4
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
